parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: ludo
    database_user: ludo
    database_password: 123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 9507536dfb5a7a3eb6dfe83bbe12780549b3ad44
